# DAZG-Orbit Project Source File
# Component: python/dazg_orbit_stage_s_q16.py
# Purpose: Fail-closed experiment, verification, or Q16 oracle component.
# Maintenance: DAZG-Orbit integration, acceleration, and reproducibility layer.
# Provenance and licenses: see NOTICE_UPSTREAM.md and LICENSE_NOTICE.md.
# Validated scope: frozen N=10 and checkpoint-013 balanced N=100.
# Security boundary: reveal correctness backend; security_claim=0.
"""Exact fixed-point Stage-S GeLU contract shared with DAZG-Orbit.

The table is generated by the active C++ HE::EvalBFEGeLUClear implementation.
Forward values therefore match the C++ Q16 contract exactly; backward uses the
GELU derivative through a straight-through estimator for fine-tuning.
"""
from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
from typing import Any, Dict, Optional, Tuple

import numpy as np
import torch
import torch.nn.functional as F

SCALE_BITS = 16
SCALE = 1 << SCALE_BITS
BITWIDTH = 32
CLIP_REAL = 8.0
CLIP_FP = int(CLIP_REAL * SCALE)
TABLE_LEN = 2 * CLIP_FP + 1
_DEFAULT_TABLE = Path(__file__).resolve().parents[1] / "experiments/n100_checkpoint013/assets/stage_s/stage_s_gelu_q16_i64.bin"
_DEFAULT_MANIFEST = Path(__file__).resolve().parents[1] / "experiments/n100_checkpoint013/assets/stage_s/stage_s_contract.json"
_CPU_TABLE: Optional[torch.Tensor] = None
_TABLE_PATH: Optional[Path] = None
_DEVICE_TABLES: Dict[Tuple[str, Optional[int]], torch.Tensor] = {}
_MANIFEST: Optional[Dict[str, Any]] = None


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def table_path() -> Path:
    raw = os.environ.get("DAZG_ORBIT_STAGE_S_Q16_TABLE", "").strip()
    return Path(raw) if raw else _DEFAULT_TABLE


def manifest_path() -> Path:
    raw = os.environ.get("DAZG_ORBIT_STAGE_S_Q16_MANIFEST", "").strip()
    return Path(raw) if raw else _DEFAULT_MANIFEST


def _load_manifest() -> Dict[str, Any]:
    global _MANIFEST
    if _MANIFEST is not None:
        return _MANIFEST
    p = manifest_path()
    if not p.is_file():
        raise FileNotFoundError(f"Stage-S manifest not found: {p}")
    obj = json.loads(p.read_text(encoding="utf-8"))
    required = {
        "schema": "dazg_orbit.stage_s.q16_contract.v743r6",
        "bitwidth": BITWIDTH,
        "scale_bits": SCALE_BITS,
        "clip_fp": CLIP_FP,
        "table_len": TABLE_LEN,
    }
    for key, expected in required.items():
        if obj.get(key) != expected:
            raise RuntimeError(f"Stage-S manifest mismatch {key}: {obj.get(key)!r} != {expected!r}")
    _MANIFEST = obj
    return obj


def _load_cpu_table() -> torch.Tensor:
    global _CPU_TABLE, _TABLE_PATH
    p = table_path()
    if _CPU_TABLE is not None and _TABLE_PATH == p:
        return _CPU_TABLE
    if not p.is_file():
        raise FileNotFoundError(
            f"Stage-S C++ table not found: {p}. Run install_wsl_v743r6.sh in Ubuntu first."
        )
    expected_bytes = TABLE_LEN * 8
    actual_bytes = p.stat().st_size
    if actual_bytes != expected_bytes:
        raise RuntimeError(f"Stage-S table size mismatch: {actual_bytes} != {expected_bytes}")
    manifest = _load_manifest()
    actual_sha = _sha256(p)
    expected_sha = str(manifest.get("table_sha256", ""))
    if expected_sha and actual_sha.lower() != expected_sha.lower():
        raise RuntimeError(f"Stage-S table SHA-256 mismatch: {actual_sha} != {expected_sha}")
    arr = np.fromfile(str(p), dtype="<i8")
    if arr.size != TABLE_LEN:
        raise RuntimeError(f"Stage-S table element count mismatch: {arr.size} != {TABLE_LEN}")
    probe_q = manifest.get("probe_q16")
    probe_y = manifest.get("probe_y_q16")
    if not isinstance(probe_q, list) or not isinstance(probe_y, list) or len(probe_q) != len(probe_y) or not probe_q:
        raise RuntimeError("Stage-S manifest is missing non-empty probe_q16/probe_y_q16 evidence")
    actual_probe = []
    for raw_q in probe_q:
        q = int(raw_q)
        if q <= -CLIP_FP:
            y = 0
        elif q >= CLIP_FP:
            y = q
        else:
            y = int(arr[q + CLIP_FP])
        actual_probe.append(y)
    expected_probe = [int(v) for v in probe_y]
    if actual_probe != expected_probe:
        raise RuntimeError(f"Stage-S table probe mismatch: {actual_probe} != {expected_probe}")
    _CPU_TABLE = torch.from_numpy(arr.copy()).to(torch.int64)
    _TABLE_PATH = p
    _DEVICE_TABLES.clear()
    return _CPU_TABLE


def _device_table(device: torch.device) -> torch.Tensor:
    key = (device.type, device.index)
    table = _DEVICE_TABLES.get(key)
    if table is None:
        table = _load_cpu_table().to(device=device, non_blocking=(device.type == "cuda"))
        _DEVICE_TABLES[key] = table
    return table


def stage_s_gelu_q16_forward(x: torch.Tensor) -> torch.Tensor:
    """Return the exact C++ Stage-S Q16 forward value, represented as float."""
    original_dtype = x.dtype
    xf = x.float()
    q = torch.round(xf * float(SCALE)).to(torch.int64)
    q = torch.clamp(q, -(1 << 31), (1 << 31) - 1)
    table = _device_table(x.device)
    idx = torch.clamp(q + CLIP_FP, 0, TABLE_LEN - 1)
    mid = table[idx]
    yq = torch.where(q <= -CLIP_FP, torch.zeros_like(q), torch.where(q >= CLIP_FP, q, mid))
    return (yq.to(torch.float32) / float(SCALE)).to(original_dtype)


def stage_s_gelu_q16_ste(x: torch.Tensor) -> torch.Tensor:
    """Exact Stage-S forward with GELU-gradient straight-through backward."""
    y_exact = stage_s_gelu_q16_forward(x)
    y_grad = F.gelu(x)
    return y_exact.detach() + y_grad - y_grad.detach()


def stage_s_contract_info() -> Dict[str, Any]:
    obj = dict(_load_manifest())
    p = table_path()
    obj.update({"table_path": str(p), "table_exists": p.is_file()})
    return obj


def selftest(device: Optional[str] = None) -> Dict[str, Any]:
    dev = torch.device(device or ("cuda" if torch.cuda.is_available() else "cpu"))
    probes_q = torch.tensor(
        [-600000, -524288, -400000, -65536, -1, 0, 1, 65536, 400000, 524288, 600000],
        dtype=torch.int64,
        device=dev,
    )
    x = probes_q.float() / float(SCALE)
    y = stage_s_gelu_q16_forward(x)
    yq = torch.round(y.float() * float(SCALE)).to(torch.int64)
    finite = bool(torch.isfinite(y).all().item())
    tails_ok = bool((yq[0] == 0).item() and (yq[-1] == probes_q[-1]).item())
    return {
        "status": "pass" if finite and tails_ok else "fail",
        "device": str(dev),
        "finite": finite,
        "tails_ok": tails_ok,
        "input_q16": probes_q.detach().cpu().tolist(),
        "output_q16": yq.detach().cpu().tolist(),
        "contract": stage_s_contract_info(),
    }


if __name__ == "__main__":
    print(json.dumps(selftest(), indent=2, ensure_ascii=False))
